name: hycop
description: Hycop Framework
version: 0.0.1
homepage: https://github.com/CretaIsland/hycop

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_functions: ^3.3.5
  device_info_plus: ^4.1.2

  logging: ^1.0.2
  flutter_riverpod: ^1.0.4
  synchronized: ^3.0.0
  uuid: ^3.0.5
  equatable: ^2.0.3
  firebase_database: ^9.0.16
  firebase: ^9.0.2
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  cloud_firestore_web: ^2.6.10
  appwrite: ^6.0.0
  routemaster: ^1.0.1
  provider: ^6.0.1
  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0

  firebase_storage: ^10.3.4
  dart_appwrite: ^6.0.0
  md5_file_checksum: ^1.0.3
  convert: ^3.0.2
  crypto: ^3.0.2
  flutter_dropzone: ^3.0.5
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
